# Generated by Django 4.0.4 on 2022-05-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
                ('num_pages', models.IntegerField()),
                ('genre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
                ('type', models.IntegerField(choices=[(1, 'Bullet'), (2, 'Food'), (3, 'Travel'), (4, 'Sport')], verbose_name='Type')),
                ('publisher', models.CharField(max_length=100, verbose_name='Publisher')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
